<?php
/**
 * Created by PhpStorm.
 * User: hahastein
 * Date: 2018/8/15
 * Time: 1:04
 */

namespace bengbeng\framework\controllers\base;


use yii\web\Controller;

/**
 * 后台基础控制器
 * Class FactoryController
 * @package bengbeng\framework\controllers\base
 */
class FactoryController extends Controller
{

    public $user_id;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->user_id = 0;
    }
}