<?php

namespace bengbeng\framework\controllers\base;

use bengbeng\framework\components\helpers\NullHelper;
use Yii;
use yii\helpers\ArrayHelper;
use yii\rest\Controller;
use yii\filters\Cors;
use yii\web\Response;
use yii\filters\ContentNegotiator;

class JsonController extends Controller{

    public $latitude;
    public $longitude;
    public $token;
    public $sign;
    public $debug;
    public $unionID;
    public $ver;
    public $os;
    public $uuid;


    protected $requestParams;
    protected $nullData;

    /**
     * 输出的内容
     * @var array
     */
    protected $outputData;
    protected $outputDataExt;
    /**
     * 输出的编码,默认0表示success 其它编码请查看const定义数值
     * @var int
     */
    protected $outputCode;

    protected $outputMessage;

    /**
     * 签名使用的前缀配置
     * @var string
     */
    protected $sign_front = '';

    /**
     * 签名使用的后缀配置
     * @var string
     */
    protected $sign_back = '';



    const CODE_SUCCESS = 10;
    const CODE_SUCCESS_CUSTOM = 200;
    const CODE_ERROR_403 = 403;
    const CODE_ERROR_4031 = 4031;
    const CODE_ERROR_404 = 404;
    const CODE_ERROR_4001 = 4001;
    const CODE_ERROR_4002 = 4002;
    const CODE_ERROR_4003 = 4003;
    const CODE_ERROR_4100 = 4100;
    const CODE_ERROR_CUSTOM = 400;

    public function init()
    {
        $this->longitude = 0;
        $this->latitude = 0;
        $this->outputCode = self::CODE_SUCCESS;
        $this->requestParams = Yii::$app->request->post();

        $this->token = Yii::$app->getRequest()->getHeaders()->get('token');//获取验证token
        $this->sign = Yii::$app->getRequest()->getHeaders()->get('sign');//签名
        $this->ver = Yii::$app->getRequest()->getHeaders()->get('ver');
        $this->os = Yii::$app->getRequest()->getHeaders()->get('os');
        $this->uuid = Yii::$app->getRequest()->getHeaders()->get('ver');

        $this->debug = NullHelper::arrayKey($this->requestParams, 'debug');//调试模式
        $this->unionID = NullHelper::arrayKey($this->requestParams, 'unionid');//用户唯一标识

        unset($this->requestParams['lat'], $this->requestParams['lng']);

        //预留验证token及签名


        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        unset($behaviors['authenticator']);
        $allowCredentials = false;
        $requestHeader = ['*'];

        if(!empty(Yii::$app->params['origin.url']) && is_array(Yii::$app->params['origin.url']) && count(Yii::$app->params['origin.url'])>0){
            $requestHeader = Yii::$app->params['origin.url'];
            $allowCredentials = true;
        }

        $behaviors['corsFilter'] = [
            'class' => Cors::className(),
            'cors' => [
                'Origin' => $requestHeader,
                'Access-Control-Allow-Origin' => $requestHeader,
                'Access-Control-Request-Method' => ['GET', 'POST', 'PUT', 'HEAD', 'OPTIONS'],
                'Access-Control-Request-Headers' => ['*'],
                'Access-Control-Allow-Credentials' => $allowCredentials,
                'Access-Control-Allow-Headers' => ['Origin, Content-Type, Accept, Referer, Authorization'],
                'Access-Control-Max-Age' => 86400
            ]
        ];
        $behaviors['contentNegotiator'] = [
            'class' => ContentNegotiator::className(),
            'formats' => [
                'application/json'=> Response::FORMAT_JSON
            ]
        ];
        return $behaviors;
    }

    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {

//        if(empty($this->token)){
//            $this->outputCode = self::CODE_ERROR_4031;
//            $this->asJson($this->splicingOutputContent())->send();
//        }

        $this->longitude = Yii::$app->request->post('lng',0);
        $this->latitude = Yii::$app->request->post('lat',0);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        return $this->splicingOutputContent();
    }

    /**
     * 拼接输出返回内容
     * @return array
     */
    private function splicingOutputContent(){
        $output['code'] = $this->outputCode;

        if($this->outputData){
            $output['data'] = $this->outputData;
        }else{
            if(isset($this->nullData)){
                $output['data'] = $this->nullData;
            }
        }

        if($this->outputDataExt){
            foreach ($this->outputDataExt as $key => $dataExt){
                if(is_string($key)) {
                    $output[$key] = $dataExt;
                }
            }
        }

        if($this->outputCode != self::CODE_SUCCESS && $this->outputCode != self::CODE_SUCCESS_CUSTOM && $this->outputCode != self::CODE_ERROR_CUSTOM){
            $output['message'] = $this->changeCodeToString();
        }else{
            if($this->outputMessage){
                $output['message'] = $this->outputMessage;
            }
        }

        return $output;
    }

    /**
     * 接口签名
     * @param array $param 原始参数
     * @return string 返回加密后的字符串
     */
    public function createSign($param){

        // 1. 对加密数组进行字典排序
        foreach ($param as $key=>$value){
            if(!empty($value)){
                $arr[$key] = $key;
            }
        }
        sort($arr);

        $str = "";
        foreach ($arr as $k => $v) {
            $str = $str.$arr[$k].'='.$param[$v].'&';
        }
        //通过Md5加密并转化为大写 大写获得签名
        $rest_str = $this->sign_front . $str . $this->sign_back;

        return strtoupper(md5($rest_str));
    }

    /**
     * @return string
     */
    private function changeCodeToString(){
        switch ($this->outputCode){
            case self::CODE_ERROR_403:
                return '您无此权限访问此接口，请确定权限是否正确';
            case self::CODE_ERROR_4031:
                return 'Token失效，请重新访问接口';
            case self::CODE_ERROR_404:
                return '没有找到任何内容';
            case self::CODE_ERROR_4001:
                return '参数问题，请检查传入参数';
            case self::CODE_ERROR_4002:
                return '未登录';
            case self::CODE_ERROR_4003:
                return '您还不是专家，请申请成为专家';
            case self::CODE_ERROR_4100:
                return '没有补全用户信息';
            default:
                return '没有定义类型，请联系管理员';
        }
    }


}


