<?php
/**
 * Created by PhpStorm.
 * User: hahastein
 * Date: 2018/9/15
 * Time: 23:53
 */

namespace bengbeng\framework\widgets\editor\summernote;


use yii\web\AssetBundle;

class SummernoteLanguageAsset extends AssetBundle
{
    public $language;
    public $sourcePath = '@bower/summernote/lang';

    public $depends = [
        'bengbeng\framework\widgets\editor\summernote\SummernoteAsset'
    ];

    public function init()
    {
        $this->language = 'zh-CN';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function registerAssetFiles($view)
    {
        $this->js[] = 'summernote-' . $this->language . '.js';
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }
}