<?php
/**
 * Created by BengBengFramework.
 * User: hahastein
 * Date: 2018-09-10
 * Time: 18:06
 */

namespace bengbeng\framework\widgets\menu;

use bengbeng\framework\models\platform\MenuARModel;
use Yii;
use yii\base\Widget;
use yii\db\ActiveRecord;

class StrongMenu extends Widget
{

    const TYPE_DEFAULT = 'layout';
    const TYPE_LEFT = 'left';
    const TYPE_TOP = 'top';
    const TYPE_RIGHT = 'right';

    public $type;
    public $isCache;

    private $menuData;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->type = self::TYPE_DEFAULT;
        $this->isCache = true;
        self::initData();
    }

    private function initData(){
        $cache = Yii::$app->cache;

        $cache_data = $cache->get('system_menu_data');

        if ($cache_data === false){
            $menuModel = new MenuARModel();
            $menuModel->showPage = false;
            $cache_data = $menuModel->dataSet(function (ActiveRecord $record){

            });
            $cache->set('system_menu_data', $cache_data);
        }

        $this->menuData = $cache_data;
    }

    public function run()
    {
        $moduleID = Yii::$app->module->id;
        $controllerID = Yii::$app->controller->id;
        $actionID = Yii::$app->controller->action->id;

        return $this->render('menu-'.$this->type, [
            'controllerID' => $controllerID,
            'actionID' => $actionID,
            'moduleID' => $moduleID
        ]);
    }
}