<?php
/**
 * Created by PhpStorm.
 * User: hahastein
 * Date: 2018/9/10
 * Time: 22:27
 */

namespace bengbeng\framework\models\platform;

use Yii;
use bengbeng\framework\base\BaseActiveRecord;

class MenuARModel extends BaseActiveRecord
{
    public static function tableName()
    {
        return '{{%menu}}'; // TODO: Change the autogenerated stub
    }
}