<?php


namespace bengbeng\framework\cms;


use bengbeng\framework\base\Modules;

class CmsBase extends Modules
{

    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function parseDataOne($item)
    {
        return parent::parseDataOne($item); // TODO: Change the autogenerated stub
    }
}