<?php


namespace bengbeng\framework\system;

use bengbeng\framework\base\Modules;

class SettingLogic extends Modules
{

    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function get(){

    }
}