<?php


namespace bengbeng\framework\user\login;


use bengbeng\framework\components\handles\WeixinHandle;

class WxSignonLogic extends SignonAbstract
{

    public $code;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->code = \Yii::$app->request->get('code', '');
        //转换微信GET的问题
//        \Yii::$app->request->setParams();

//        $this->userModel->setScenario('wx');


    }

    public function login()
    {
        try {
            $wxInfo = WeixinHandle::getWxUnionCode();
            $userInfo = $this->userModel->info(['wx_unioncode' => $wxInfo['unionid']]);

            if ($userInfo) {
                $userInfo = $userInfo->toArray();

                //验证状态码
                if($userInfo['user_state'] === 0){
                    throw new \Exception('用户被禁止登录,请联系管理员');
                }else if($userInfo['user_state'] == 10){
                    $this->code = 4100;
                    $this->parseUserInfo($userInfo);
                    $this->returnData = $userInfo;
                    throw new \Exception('用户未补全信息，请补全信息');
                }

                if($this->endLoginCallback){
                    $userInfo = call_user_func($this->endLoginCallback, $userInfo);
                }

                //登录成功直接返回用户信息
                $this->parseUserInfo($userInfo);
                return $userInfo;

            }else{

                $params['openid'] = $wxInfo['openid'];
                $params['unioncode'] = $wxInfo['unionid'];
                $params['avatar_head'] = $wxInfo['avatar'];
                $params['user_sex'] = $wxInfo['sex'];
                $params['nickname'] = $wxInfo['nickname'];
                $this->code = 4101;
                $this->returnData = $params;
                throw new \Exception('用户未绑定手机，请去绑定手机');
            }

        }catch (\Exception $ex){
            $this->error = $ex->getMessage();
            return false;
        }
    }

    public function logout()
    {
        // TODO: Implement logout() method.
    }
}