<?php


namespace bengbeng\framework\user;


use bengbeng\framework\base\Modules;
use bengbeng\framework\models\UserARModel;

class UserBase extends Modules
{

    /**
     * @var UserARModel $userModel
     */
    protected $userModel;

    protected $model;
    protected $saveParams;

    protected function init()
    {
        $this->user = new UserARModel();
        parent::init(); // TODO: Change the autogenerated stub

    }

    protected function parseDataOne($item)
    {
        return parent::parseDataOne($item); // TODO: Change the autogenerated stub
    }

    /**
     * 桥接别的Logic
     * @return User
     */
    protected function bridge(){
        return new User();
    }

}