<?php
/**
 * Created by PhpStorm.
 * User: bengbeng
 * Date: 2018/8/19
 * Time: 上午10:06
 */

namespace bengbeng\framework\models;


use bengbeng\framework\base\BaseActiveRecord;

class PlatformStatisticsARModel extends BaseActiveRecord
{

    public static function tableName()
    {
        return '{{%plat_statistics}}'; // TODO: Change the autogenerated stub
    }


}