<?php


namespace bengbeng\framework\models;


use bengbeng\framework\base\BaseActiveRecord;

/**
 * Class UserStatisticArModel
 * @property int $user_id               用户ID
 * @property int $my_reply_num          我的回复数
 * @property int $my_question_num       我的问题数
 * @property int $order_wait_deliver    等待发货订单数
 * @property int $order_wait_receive    等待收货订单数
 * @property int $order_count           订单总数
 * @property int $fav_count             收藏总数
 * @property int $comment_count         评论总数
 * @package bengbeng\framework\models
 */
class UserStatisticArModel extends BaseActiveRecord
{
    public static function tableName()
    {
        return '{{%user_statistic}}'; // TODO: Change the autogenerated stub
    }
}