<?php


namespace bengbeng\framework\models;


use bengbeng\framework\base\BaseActiveRecord;

class UserRelationARModel extends BaseActiveRecord
{
    public static function tableName()
    {
        return '{{%user_relation}}'; // TODO: Change the autogenerated stub
    }
}