<?php


namespace bengbeng\framework\models;


use bengbeng\framework\base\BaseActiveRecord;
use yii\db\ActiveQuery;

class UserGroupUserARModel extends BaseActiveRecord
{
    public static function tableName()
    {
        return '{{%im_group_user}}'; // TODO: Change the autogenerated stub
    }

    public function findUserNotExistByID($groupID, $ids){
        return self::dataSet(function (ActiveQuery $query) use($groupID, $ids){
            $query->where(['group_id' => $groupID]);
            $query->andWhere(['not in', 'user_id', $ids]);
        });
    }
}