<?php


namespace bengbeng\framework\models;


use bengbeng\framework\base\BaseActiveRecord;

/**
 * Class UserRelationARModel
 * @property integer $relation_id
 * @property integer $send_user_id
 * @property integer $accept_user_id
 * @property int $status
 * @property integer $createtime
 * @property integer $updatetime
 * @package bengbeng\framework\models
 */
class UserRelationARModel extends BaseActiveRecord
{
    public static function tableName()
    {
        return '{{%user_relation}}'; // TODO: Change the autogenerated stub
    }

    /**
     * @param $myID
     * @param $friendID
     * @return UserRelationARModel|null
     */
    public function findRelationByTowID($myID, $friendID){
        return self::info([
            'send_user_id' => $myID,
            'accept_user_id' => $friendID
        ]);
    }
}